services:
  - type: web
    name: erp-php
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false # set this in Render dashboard or paste generated key
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: erp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: erp-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: erp-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: erp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: erp-db
          property: password

databases:
  - name: erp-db
    plan: free
