services:
  - type: web
    name: erp-php
    env: docker
    plan: free
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false # Paste or generate one in Render dashboard
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: erp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: erp-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: erp-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: erp-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: erp-db
          property: password
    postdeploy:
      - php artisan key:generate --force
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan migrate --force

databases:
  - name: erp-db
    plan: free
